### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by OUAISPASMALCA** [Azuxul/cahier-de-prepa-downloader#4]
Bonjour,
pourriez-vous m'expliquez comment lancer se programme en détails je n'y arrive pas
Cordialement

**Comment by Azuxul** [comment]
Bonjour,

Le détail est décrit dans le fichier [README.md](https://github.com/Azuxul/cahier-de-prepa-downloader/blob/master/README.md)

Pour faire simple il faut installer Python 3 https://www.python.org/downloads/

Ensuite il faut lancer un terminal puis exécuter les commandes suivantes :

```
pip install cdpDumpingUtils
```

Il faut ensuite lancer le script avec 
```
cdpDumpingUtils -u https://cahier-de-prepa.fr/XXX/ -l username -p password -o ./output
```

en remplaçant username avec le nom d'utilisateur, password avec le mot de passe et https://cahier-de-prepa.fr/XXX/ avec l'url à utiliser
